### ISSUE TITLE
Error when trying to read CNES STPI2201.dbc

### ISSUE THREAD

**Issue by gabrielfmcoelho** [danicat/pysus#1]
Transforming STPI2201.dbc
Traceback (most recent call last):
  File "/mnt/c/Users/gcmas/OneDrive/Área de Trabalho/S3 Biotech/Desenvolvimento/ETL Growth/main.py", line 156, in <module>
    cnes_etl.run()
  File "/mnt/c/Users/gcmas/OneDrive/Área de Trabalho/S3 Biotech/Desenvolvimento/ETL Growth/CNES/etl.py", line 80, in run
    self.transform()
  File "/mnt/c/Users/gcmas/OneDrive/Área de Trabalho/S3 Biotech/Desenvolvimento/ETL Growth/CNES/etl.py", line 64, in transform
    transform.transform_dbc_files(self.path_temp, PATH_UNZIPED, self.target_files)
  File "/mnt/c/Users/gcmas/OneDrive/Área de Trabalho/S3 Biotech/Desenvolvimento/ETL Growth/CNES/transform.py", line 27, in transform_dbc_files
    df = pd.DataFrame(read_dbc(path_temp + file))
  File "/usr/local/lib/python3.10/dist-packages/dbfread-2.0.7-py3.10.egg/dbfread/dbf.py", line 122, in __init__
    self._read_field_headers(infile)
  File "/usr/local/lib/python3.10/dist-packages/dbfread-2.0.7-py3.10.egg/dbfread/dbf.py", line 235, in _read_field_headers
    field.name = self._decode_text(field.name.split(b'\0')[0])
  File "/usr/local/lib/python3.10/dist-packages/dbfread-2.0.7-py3.10.egg/dbfread/dbf.py", line 215, in _decode_text
    return data.decode(self.encoding, errors=self.char_decode_errors)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xba in position 3: ordinal not in range(128)

**Comment by danicat** [comment]
I don't know what I am seeing here. If you want my help I need you to help me help you. What is the smallest snippet of code that reproduces this error? What were you trying to do? What were you expecting to see?

I need something like this https://github.com/stevemao/github-issue-templates/blob/master/simple/ISSUE_TEMPLATE.md
